# Site settings
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

#plugins
plugins:
  - jekyll-archives
  
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
jekyll-archives:
  enabled: 
    - categories
    - tags
    - month
    - year
  layouts:
    category: category
    tag: category
    month: month
    year: month
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'
    month: '/post/:year/:month/'
    year: '/post/:year/'

#custom site data
collections:
  authors:
    output: true
    

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:year/:month/:day/:title
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      