# Site settings
baseurl: "/bh-blog" # the subpath of your site, e.g. /blog
url: "http://benny123tw.github.io/bh-blog" # the base hostname & protocol for your site, e.g. http://example.com
#Google Analytics
google_analytics: UA-128395546-1

# Build settings
markdown: kramdown

#plugins
plugins:
  - jekyll-archives
  - jekyll-sitemap
  
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

jekyll-archives:
  enabled:
    - categories
    - tags
    - month
    - year
  layouts:
    category: category
    tag: category
    month: month
    year: month
  permalinks:
    category: '/categories/:name'
    tag: '/tags/:name'
    month: '/post/:year/:month'
    year: '/post/:year'

#custom site data
collections:
  authors:
    output: true


defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
      comments: true
    values:
      layout: "post"
      permalink: /:categories/:year/:month/:day/:title
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      
